"""empty message

Revision ID: 00b6954f52f2
Revises: 175f00c2dcbd
Create Date: 2023-07-10 02:19:24.288288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b6954f52f2'
down_revision = '175f00c2dcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comics_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_history', schema=None) as batch_op:
        batch_op.drop_column('comics_num')

    # ### end Alembic commands ###
