"""empty message

Revision ID: 175f00c2dcbd
Revises: 7c6fa53a1a75
Create Date: 2023-07-10 01:08:31.776083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175f00c2dcbd'
down_revision = '7c6fa53a1a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', name='crawl_status_enum'), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_history')
    # ### end Alembic commands ###
