"""empty message

Revision ID: 34c8c3cdb5e1
Revises: 86837045750e
Create Date: 2023-07-16 03:54:12.339877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34c8c3cdb5e1'
down_revision = '86837045750e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abj_management_number', sa.String(length=255), nullable=True))
        batch_op.drop_column('abj_manegement_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abj_manegement_number', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('abj_management_number')

    # ### end Alembic commands ###
