"""empty message

Revision ID: 7c6fa53a1a75
Revises: fc8b2b1a0d44
Create Date: 2023-07-09 21:45:42.667516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6fa53a1a75'
down_revision = 'fc8b2b1a0d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
