"""Initial migration.

Revision ID: 86837045750e
Revises: 
Create Date: 2023-07-16 03:01:31.285443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86837045750e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abj_manegement_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('service_type', sa.Enum('基本無料', '最新話無料', name='service_type_enum'), nullable=True))
        batch_op.alter_column('platform_type',
               existing_type=mysql.ENUM('app', 'web'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('platform_type',
               existing_type=mysql.ENUM('app', 'web'),
               nullable=False)
        batch_op.drop_column('service_type')
        batch_op.drop_column('company_name')
        batch_op.drop_column('abj_manegement_number')

    # ### end Alembic commands ###
