"""empty message

Revision ID: b5c202f7e58e
Revises: bf9fc6cbd450
Create Date: 2023-07-23 04:03:37.643378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5c202f7e58e'
down_revision = 'bf9fc6cbd450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crawl_status', sa.String(length=30), nullable=True))

    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('raw_author', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('comic_ibfk_1', type_='foreignkey')
        batch_op.drop_column('sub_author')
        batch_op.drop_column('app_id')
        batch_op.drop_column('crawled_at')
        batch_op.drop_column('main_author')
        batch_op.drop_column('url')

    with op.batch_alter_table('crawl_history', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_history', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('main_author', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('crawled_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('app_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sub_author', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('comic_ibfk_1', 'app', ['app_id'], ['id'])
        batch_op.drop_column('raw_author')
        batch_op.drop_column('author')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('crawl_status')

    op.drop_table('crawl')
    # ### end Alembic commands ###
