"""'initial_migration'

Revision ID: fc8b2b1a0d44
Revises: 
Create Date: 2023-07-09 20:54:27.457149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc8b2b1a0d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_type', sa.Enum('app', 'web', name='platform_type_enum'), nullable=False))
        batch_op.drop_column('platform_type_id')

    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crawled_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_column('crawled_at')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_type_id', mysql.ENUM('app', 'web'), nullable=False))
        batch_op.drop_column('platform_type')

    # ### end Alembic commands ###
